### ISSUE TITLE
Empty error when attempting to sign using the updated ledger firmware

### ISSUE THREAD

**Issue by evan-forbes** [cosmos/ledger-cosmos#100]
Previous to the 2.2.2 ledger nano X firmware upgrade, we were able to sign transactions via the cli. Now, after updating to 2.2.2, the ledger is unable to sign and nothing happens. please see https://github.com/celestiaorg/celestia-app/issues/2650 for more details.

From that issue:

## Summary of Bug
When attempting to sign any TX with ledger hardware wallet an empty error is thrown with a second delay.

> celestia-appd tx sign tx-test.json --from ledger-test   --chain-id="mocha-4" --offline -s 0 -a 0 --ledger
Default sign-mode 'direct' not supported by Ledger, using sign-mode 'amino-json'.
Error:
I tried playing around with various options and flags - the result is always the same

**Comment by keyleu** [comment]
Hello, we are having the same issue on our chain (Coreum) with CLI.

Actually the issue for me is not with the firmware update but with the app version. The previous ledger-cosmos app version (2.34.9) in the marketplace worked without issues with CLI. In fact, if I take that version from the repository and compile it and install it using the ledger extension on my device with the new firmware, it still works.

The problem comes when I take the app version 2.34.12 (or any superior version that is not released yet, 2.35.*), the CLI is not compatible anymore. We get the same error as described above. After attempting to sign a message, it will throw an empty error without any description.

**Comment by evan-forbes** [comment]
hey @keyleu this only works for apps built in go afaiu, but we just used a version of the sdk that bump [this dep to v0.13.1](https://github.com/celestiaorg/celestia-app/blob/2b8cc9e23826ccb658b7dd5aa6cd51a0921a0c29/go.mod#L48) and the issue was resolved for us. I actually forgot to close this!

please feel free to reopen @keyleu if this is still an issue for you
