### ISSUE TITLE
Expert Mode Not Functioning with Ledger Nano X

### ISSUE THREAD

**Issue by mconstant** [cosmos/ledger-cosmos#103]
Expert Mode does not work with the Ledger Nano X

**Comment by ftheirs** [comment]
Hi @mconstant! What do you mean by "does not work"? Can you describe a little bit more the issue you're facing?

**Comment by mconstant** [comment]
Absolutely @ftheirs .

Let’s first talk about what Expert Mode is like when it works.

With the Cosmos Ledger App on a Ledger Nano S, users can enable Expert Mode and click both buttons twice to skip all the screens you would normally have to skip through with right button presses and quickly sign.

This does not work on the Ledger Nano X. On the Nano X, when a user enables Expert Mode in the Cosmos Ledger App, this does not work and the user has to click through everything with the right button.

**Comment by ftheirs** [comment]
Hello @mconstant, 

Expert mode is designed for advanced users, offering a comprehensive view of all transaction fields. Enabling this mode will present more screens for review, providing in-depth information. 
Some specific apps had a feature similar to what you described when dealing with more than  30~50 screens and mainly displaying non-human-readable data. However, for most apps, this feature has been disabled due to the mandatory manual review required from users before signing.

Why would you need to skip all the fields instead of verifying the transaction?

**Comment by mconstant** [comment]
@ftheirs 

SCRT Network is horribly unusable without this feature to skip extra clicking. Which is apparently undocumented or unsupported by your knowledge.

You may want to try using some SCRT Network apps with Expert Mode Enabled on a Nano S to see how it makes things better.  It also makes it easier to use Osmosis and it is recommended in their Ledger setup documentation.

Note that the skip feature only applies on the Nano S.

see the bonus tip section on this page
https://support.osmosis.zone/tutorials/ledgersetupguide

<img width="581" alt="image" src="https://github.com/cosmos/ledger-cosmos/assets/85532172/e39217ed-5328-4865-9bec-5dc4a46ecd3b">

**Comment by ftheirs** [comment]
Around 20 screens to review, that's not that much and there you have important information that NEEDS to ve verified by the user. I'll close this issue but feel free to open a new one if you'd like to collaborate to improve the UI since it doesn't look very user friendly with these kind of transactions.
