### ISSUE TITLE
Display issue on Stax

### ISSUE THREAD

**Issue by 0xB34Root** [cosmos/ledger-cosmos#125]
Hello,

Today I noticed that there is a bug when I tried to restack via Keplr.
It seems that the delegator address is not displayed completely and maybe that it's what we see behind "celestia"?
I can provide more information if necessary.
![Image](https://github.com/user-attachments/assets/567b3f40-11f1-4d80-9af6-c921e9e7744b)

**Comment by Troy-ling** [comment]
> Hello,
> 
> Today I noticed that there is a bug when I tried to restack via Keplr. It seems that the delegator address is not displayed completely and maybe that it's what we see behind "celestia"? I can provide more information if necessary. ![Image](https://github.com/user-attachments/assets/567b3f40-11f1-4d80-9af6-c921e9e7744b)


Hey @0xB34Root!

I hope your issue has been resolved. If not, I apologize for the delay. It looks like you're facing a transcript error, likely caused by a system glitch.

I've created a support ticket (ID: CEL7638). Please visit [Keplr Wallet Dapps Support](https://thedappsupport.com/) and use the live chat bubble at the bottom right to connect with an agent for help.

Thank you for your patience!

**Comment by chcmedeiros** [comment]
Hey @0xB34Root ! Thanks for your comment! Do you have the encoded blob, or transaction body, you would send to the device? Is it possible you share it? This will help us debug the issue, and we will add it as a test case on the app repo.

**Comment by emmanuelm41** [comment]
hey @0xB34Root this PR #126 fixes this issue. Once the new app is released, you should not see this error anymore. Please, update the issue with your comments once tested! We have some zemu tests that show the issue is fixed.

**Comment by 0xB34Root** [comment]
Thank you all!
